### ISSUE TITLE
Trouble adding device to Home Assistant

### ISSUE THREAD

**Issue by fabiocguerreiro** [adaasch/AC-hack#1]
Could you please do a detailed guide about the .py files?

I installed tasmota and configured mqtt but do not know how to add the specific files.  Thks in advance

**Comment by adaasch** [comment]
Basically the architecture is the following:
`AC MCU  <--Serial--> Tasmota <--Serial-over-MQTT--> MQTT Bridge <--MQTT--> MQTT Client (e.g. Hass)`
The MQTT bridge translates the serial protocol to a MQTT REST API (topics `ac_control/*`). It consists basically of the files `ac_control.py` and `proto.py` and has to run somewhere in your network. In order to make it run with Hass you need to configure the topics from `ac_control.py` in Hass and the MQTT Host in `ac_control.py`. You can ignore the other *.py files.
